# # list & tuple
# friends = ["apple","akash",5,234.89,False]

# print(friends[0])
# friends[0] = "Graphes"
# print(friends[0:3])
# print(friends)
# friends.append("harry")
# print(len(friends))
# l1 = [1,4,7,89,1,0]
# # l1.sort()
# # l1.reverse()
# l1.insert(3,33333)
# print(l1)
# print(l1.pop(3))
# l1.remove(7)
# print(l1)

# a= (1,1,1,2,3,"kiler",34.5)
# print(type(a))
# print(a)
# no = a.count(1)
# i = a.index(3)
# print(9 in a)
# print(no)
# print(i)
# fruits = []
# f0 = int(input("Enter fruit nam)e: ")
# fruits.append(f0)
# f1 = int(input("Enter fruit nam)e: ")
# fruits.append(f1)
# f2 = int(input("Enter fruit nam)e: ")
# fruits.append(f2)
# f3 = int(input("Enter fruit nam)e: ")
# fruits.append(f3)
# f4 = int(input("Enter fruit nam)e: ")
# fruits.append(f4)
# f5 = int(input("Enter fruit nam)e: ")
# fruits.append(f5)
# f6 = int(input("Enter fruit nam)e: ")
# fruits.append(f6)
# print(fruits)

marks = []
f0 = int(input("Enter marks: "))
marks.append(f0)
f1 = int(input("Enter marks: "))
marks.append(f1)
f2 = int(input("Enter marks: "))
marks.append(f2)
f3 = int(input("Enter marks: "))
marks.append(f3)
f4 = int(input("Enter marks: "))
marks.append(f4)
f5 = int(input("Enter marks: "))
marks.append(f5)
f6 = int(input("Enter marks: "))
marks.append(f6)
print(marks)
marks.sort()
print(marks)
